apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          # image: <YOUR_DOCKER_USERNAME>/hello-world-app:latest
          # command: ["java", "-cp", "app.jar", "com.demo.Main"]
          image: imageupdate.azurecr.io/myimage:6
          ports:
            - containerPort: 8080
