name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Log in to Azure Container Registry
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 5. Build & Push Docker image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/hello-world-app
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      # 6. Update Kubernetes manifests
      - name: Update Kubernetes manifest
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE_NAME }}:${{ env.TAG }}|g" manifests/deployment.yaml

      # 7. Commit & Push manifest changes
      - name: Commit manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image to ${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          git push
